ZEEKR_SERVICEID_RCS = "RCS"    # Remote Charge Service (charge start/stop/limit)
ZEEKR_SERVICEID_RDC = "RDC"    # Remote Door Close (charge lid close)
ZEEKR_SERVICEID_RDL = "RDL"    # Remote Door Lock (all doors)
ZEEKR_SERVICEID_RDL_2 = "RDL_2"  # Remote Door Lock 2 (boot/trunk close)
ZEEKR_SERVICEID_RDO = "RDO"    # Remote Door Open (charge lid open)
ZEEKR_SERVICEID_RDU = "RDU"    # Remote Door Unlock (all doors, frunk)
ZEEKR_SERVICEID_RDU_2 = "RDU_2"  # Remote Door Unlock 2 (boot/trunk open)
ZEEKR_SERVICEID_RHL = "RHL"    # Remote Horn/Light
ZEEKR_SERVICEID_RWS = "RWS"    # Remote Window/Sunshade
ZEEKR_SERVICEID_PCM = "PCM"    # Parking Comfort Mode
ZEEKR_SERVICEID_RSM = "RSM"    # Remote Sensing Mode
ZEEKR_SERVICEID_ZAF = "ZAF"    # ZEEKR Air Function (climate/defrost/steering heat)
